"""auto update

Revision ID: 0f775583cf2e
Revises: de18c6f82906
Create Date: 2026-07-27 14:52:05.503056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f775583cf2e'
down_revision: Union[str, Sequence[str], None] = 'de18c6f82906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_register_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_register_transactions_id'), 'cash_register_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_cash_register_transactions_passenger_id'), 'cash_register_transactions', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_cash_register_transactions_ride_id'), 'cash_register_transactions', ['ride_id'], unique=False)
    op.create_table('company_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('last_updated_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_accounts_id'), 'company_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_accounts_id'), table_name='company_accounts')
    op.drop_table('company_accounts')
    op.drop_index(op.f('ix_cash_register_transactions_ride_id'), table_name='cash_register_transactions')
    op.drop_index(op.f('ix_cash_register_transactions_passenger_id'), table_name='cash_register_transactions')
    op.drop_index(op.f('ix_cash_register_transactions_id'), table_name='cash_register_transactions')
    op.drop_table('cash_register_transactions')
    # ### end Alembic commands ###