"""auto update

Revision ID: 2f4f185451df
Revises: 0f775583cf2e
Create Date: 2026-07-27 15:14:10.054331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f4f185451df'
down_revision: Union[str, Sequence[str], None] = '0f775583cf2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_alerts_id'), 'cash_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_cash_alerts_passenger_id'), 'cash_alerts', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_cash_alerts_ride_id'), 'cash_alerts', ['ride_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_alerts_ride_id'), table_name='cash_alerts')
    op.drop_index(op.f('ix_cash_alerts_passenger_id'), table_name='cash_alerts')
    op.drop_index(op.f('ix_cash_alerts_id'), table_name='cash_alerts')
    op.drop_table('cash_alerts')
    # ### end Alembic commands ###