"""auto update

Revision ID: 3c4356a180fd
Revises: 7503d969262d
Create Date: 2026-07-27 10:24:11.016014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4356a180fd'
down_revision: Union[str, Sequence[str], None] = '7503d969262d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('currency_symbol', sa.String(), nullable=False),
    sa.Column('base_fare', sa.Integer(), nullable=False),
    sa.Column('price_per_km', sa.Integer(), nullable=False),
    sa.Column('price_per_min', sa.Integer(), nullable=False),
    sa.Column('minimum_fare', sa.Integer(), nullable=False),
    sa.Column('airport_surcharge', sa.Integer(), nullable=True),
    sa.Column('night_multiplier', sa.Float(), server_default='1.5', nullable=True),
    sa.Column('night_start_hour', sa.Integer(), server_default='22', nullable=True),
    sa.Column('night_end_hour', sa.Integer(), server_default='6', nullable=True),
    sa.Column('daily_target', sa.Integer(), nullable=True),
    sa.Column('rounding_unit', sa.Integer(), server_default='100', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_tariffs_id'), 'country_tariffs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_tariffs_id'), table_name='country_tariffs')
    op.drop_table('country_tariffs')
    # ### end Alembic commands ###