"""auto update

Revision ID: 53b62d51bfa7
Revises: 71c65ca34840
Create Date: 2026-07-27 09:44:05.668373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b62d51bfa7'
down_revision: Union[str, Sequence[str], None] = '71c65ca34840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_addresses_id'), 'saved_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_saved_addresses_user_id'), 'saved_addresses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_addresses_user_id'), table_name='saved_addresses')
    op.drop_index(op.f('ix_saved_addresses_id'), table_name='saved_addresses')
    op.drop_table('saved_addresses')
    # ### end Alembic commands ###