"""auto update

Revision ID: 609cc9c8e927
Revises: 054022893f10
Create Date: 2026-08-04 02:36:10.551122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609cc9c8e927'
down_revision: Union[str, Sequence[str], None] = '054022893f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_alerts', sa.Column('user_id', sa.String(), nullable=False))
    op.alter_column('user_alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_alerts', 'is_dismissed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_user_alerts_user_id'), 'user_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_alerts_user_id'), table_name='user_alerts')
    op.alter_column('user_alerts', 'is_dismissed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user_alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_column('user_alerts', 'user_id')
    # ### end Alembic commands ###