"""auto update

Revision ID: 6c6d1778fac1
Revises: ae9cf4a66d13
Create Date: 2026-08-28 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6d1778fac1'
down_revision: Union[str, Sequence[str], None] = 'ae9cf4a66d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_otp_requests', sa.Column('channel', sa.String(), nullable=True))
    op.execute("UPDATE phone_otp_requests SET channel = 'sms' WHERE channel IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_otp_requests', 'channel')
    # ### end Alembic commands ###
