"""auto update

Revision ID: 71c65ca34840
Revises: 77047a776859
Create Date: 2026-07-27 04:20:57.004785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c65ca34840'
down_revision: Union[str, Sequence[str], None] = '77047a776859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_positions_driver_id'), 'vehicle_positions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_positions_id'), 'vehicle_positions', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_positions_ride_id'), 'vehicle_positions', ['ride_id'], unique=False)
    op.create_index(op.f('ix_vehicle_positions_vehicle_id'), 'vehicle_positions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_positions_vehicle_id'), table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions_ride_id'), table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions_id'), table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions_driver_id'), table_name='vehicle_positions')
    op.drop_table('vehicle_positions')
    # ### end Alembic commands ###