"""auto update

Revision ID: a6c65b796485
Revises: 
Create Date: 2026-07-24 10:18:42.674360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c65b796485'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='offline', nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), server_default='5.0', nullable=True),
    sa.Column('total_rides', sa.Integer(), server_default='0', nullable=True),
    sa.Column('daily_earnings', sa.Integer(), server_default='0', nullable=True),
    sa.Column('zone', sa.String(), server_default='douala', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_vehicle_id'), 'drivers', ['vehicle_id'], unique=False)
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('wallet_balance', sa.Integer(), server_default='0', nullable=True),
    sa.Column('has_pending_debt', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('debt_amount', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_rides', sa.Integer(), server_default='0', nullable=True),
    sa.Column('co2_saved', sa.Float(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_id'), 'passengers', ['id'], unique=False)
    op.create_table('recharges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('price_per_kwh', sa.Float(), server_default='106', nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=False),
    sa.Column('km_counter', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recharges_driver_id'), 'recharges', ['driver_id'], unique=False)
    op.create_index(op.f('ix_recharges_id'), 'recharges', ['id'], unique=False)
    op.create_index(op.f('ix_recharges_vehicle_id'), 'recharges', ['vehicle_id'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=True),
    sa.Column('pickup_address', sa.String(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('destination_address', sa.String(), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('estimated_price', sa.Integer(), nullable=True),
    sa.Column('final_price', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(), server_default='wallet', nullable=True),
    sa.Column('payment_status', sa.String(), server_default='pending', nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('km_start', sa.Integer(), nullable=True),
    sa.Column('km_end', sa.Integer(), nullable=True),
    sa.Column('co2_saved', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    op.create_index(op.f('ix_rides_passenger_id'), 'rides', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_rides_vehicle_id'), 'rides', ['vehicle_id'], unique=False)
    op.create_table('tariff_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_fare', sa.Integer(), server_default='500', nullable=True),
    sa.Column('price_per_km', sa.Integer(), server_default='350', nullable=True),
    sa.Column('price_per_min', sa.Integer(), server_default='50', nullable=True),
    sa.Column('minimum_fare', sa.Integer(), server_default='1000', nullable=True),
    sa.Column('airport_surcharge', sa.Integer(), server_default='2000', nullable=True),
    sa.Column('night_multiplier', sa.Float(), server_default='1.5', nullable=True),
    sa.Column('night_start_hour', sa.Integer(), server_default='22', nullable=True),
    sa.Column('night_end_hour', sa.Integer(), server_default='6', nullable=True),
    sa.Column('co2_saved_per_km', sa.Float(), server_default='120', nullable=True),
    sa.Column('daily_target', sa.Integer(), server_default='30000', nullable=True),
    sa.Column('alert_threshold_percent', sa.Integer(), server_default='85', nullable=True),
    sa.Column('zone', sa.String(), server_default='douala', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_settings_id'), 'tariff_settings', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fleet_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='available', nullable=True),
    sa.Column('km_counter', sa.Integer(), server_default='0', nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('battery_level', sa.Integer(), server_default='100', nullable=True),
    sa.Column('zone', sa.String(), server_default='douala', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_fleet_id'), 'vehicles', ['fleet_id'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_passenger_id'), 'wallet_transactions', ['passenger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_passenger_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fleet_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_tariff_settings_id'), table_name='tariff_settings')
    op.drop_table('tariff_settings')
    op.drop_index(op.f('ix_rides_vehicle_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_passenger_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_recharges_vehicle_id'), table_name='recharges')
    op.drop_index(op.f('ix_recharges_id'), table_name='recharges')
    op.drop_index(op.f('ix_recharges_driver_id'), table_name='recharges')
    op.drop_table('recharges')
    op.drop_index(op.f('ix_passengers_id'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_drivers_vehicle_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###