"""auto update

Revision ID: ae9cf4a66d13
Revises: 609cc9c8e927
Create Date: 2026-08-13 02:31:43.401446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9cf4a66d13'
down_revision: Union[str, Sequence[str], None] = '609cc9c8e927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_otp_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=True),
    sa.Column('request_ip', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_otp_requests_id'), 'phone_otp_requests', ['id'], unique=False)
    op.add_column('passengers', sa.Column('city', sa.String(), nullable=True))
    op.alter_column('passengers', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('passengers', 'wallet_balance',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('passengers', 'has_pending_debt',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('passengers', 'debt_amount',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('passengers', 'total_rides',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('passengers', 'co2_saved',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('passengers', 'co2_saved',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('passengers', 'total_rides',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('passengers', 'debt_amount',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('passengers', 'has_pending_debt',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('passengers', 'wallet_balance',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('passengers', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('passengers', 'city')
    op.drop_index(op.f('ix_phone_otp_requests_id'), table_name='phone_otp_requests')
    op.drop_table('phone_otp_requests')
    # ### end Alembic commands ###