"""auto update

Revision ID: bab73fa9de0e
Revises: 2f4f185451df
Create Date: 2026-07-30 04:13:48.991122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab73fa9de0e'
down_revision: Union[str, Sequence[str], None] = '2f4f185451df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_fingerprint', sa.String(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.Column('has_debt_flag', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('debt_amount_at_register', sa.Integer(), server_default='0', nullable=True),
    sa.Column('install_count', sa.Integer(), server_default='1', nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('block_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_registry_id'), 'device_registry', ['id'], unique=False)
    op.create_index(op.f('ix_device_registry_passenger_id'), 'device_registry', ['passenger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_registry_passenger_id'), table_name='device_registry')
    op.drop_index(op.f('ix_device_registry_id'), table_name='device_registry')
    op.drop_table('device_registry')
    # ### end Alembic commands ###